version: '3.7'

services:
    db:
        image: postgres:12.0-alpine
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=5RLHLM"ACmQvtEne&%
            - POSTGRES_DB=rss_db
        ports:
            - 5432:5432

    redis:
        image: redis:6.2.3-alpine

        ports:
            - 6379:6379
