ACCESS_TOKEN_LENGTH: int = 32
ACCESS_TOKEN_EXPIRATION_INTERVAL: int = 600
REFRESH_TOKEN_LENGTH: int = 32
REFRESH_TOKEN_EXPIRATION_INTERVAL: int = 28800
# number of old RSS transfer to user feed after subscription
OLD_RSS_ADD_TO_FEED_WINDOW: int = 10000
# feed remember time to avoid redundancy
FEED_STORE_TIME_OUT = 86400

MINIMUM_PASSWORD_CHARACTERS = 10
SOURCES_CHUNK_LIMIT = 10000
JOB_CONCURRENCY = 16
